services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: zd-api-service
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env.docker
    environment:
    - NODE_ENV=production
    networks:
      - zd-network
  
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: zd-client-service
    ports:
      - "3000:3000"
    environment:
    - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - zd-network

networks:
  zd-network:
    driver: bridge